-- 1. Reference Tables (No dependencies)
CREATE TABLE roles (
    id_role INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre_role VARCHAR(255) NOT NULL
);

CREATE TABLE categories (
    id_categorie INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre_categorie VARCHAR(255) NOT NULL
);

CREATE TABLE especes (
    id_espece INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_espece VARCHAR(255) NOT NULL,
    taille_minimale FLOAT,
    coefficient_points INT
);

CREATE TABLE badges (
    id_badge INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre_badge VARCHAR(255) NOT NULL,
    icone_badge VARCHAR(255),
    min_score INT
);

-- 2. User Hierarchy (Abstract User Implementation)
CREATE TABLE users (
    id_user INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_user VARCHAR(255) NOT NULL,
    email_user VARCHAR(255) UNIQUE NOT NULL,
    password_user VARCHAR(255) NOT NULL,
    id_role INT REFERENCES roles(id_role) ON DELETE SET NULL
);

CREATE TABLE admins (
    id_user INT PRIMARY KEY REFERENCES users(id_user) ON DELETE CASCADE,
    niveau_acces INT DEFAULT 1
);

CREATE TABLE pecheurs (
    id_user INT PRIMARY KEY REFERENCES users(id_user) ON DELETE CASCADE,
    region VARCHAR(255),
    specialite VARCHAR(255),
    photo_pecheur VARCHAR(255),
    statut_pecheur VARCHAR(50)
);

CREATE TABLE fans (
    id_user INT PRIMARY KEY REFERENCES users(id_user) ON DELETE CASCADE,
    statut_fan VARCHAR(50)
);

-- 3. Competition & Organization
CREATE TABLE competitions (
    id_competition INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre_competition VARCHAR(255) NOT NULL,
    lieu_competition VARCHAR(255),
    date_debut DATE,
    date_fin DATE,
    type_competition VARCHAR(100),
    statut_competition VARCHAR(50),
    nbr_manches INT,
    max_participants INT,
    id_categorie INT REFERENCES categories(id_categorie) ON DELETE SET NULL
);

-- Specializations of Competition
CREATE TABLE championats (
    id_competition INT PRIMARY KEY REFERENCES competitions(id_competition) ON DELETE CASCADE
);

CREATE TABLE reglements (
    id_competition INT PRIMARY KEY REFERENCES competitions(id_competition) ON DELETE CASCADE
);

CREATE TABLE manches (
    id_manche INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre_manche VARCHAR(255),
    ordre_manche INT,
    lieu_manche VARCHAR(255),
    description_manche TEXT,
    id_competition INT REFERENCES competitions(id_competition) ON DELETE CASCADE
);

CREATE TABLE equipes (
    id_equipe INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_equipe VARCHAR(255) NOT NULL,
    photo_equipe VARCHAR(255),
    description_equipe TEXT
);

-- Association Class: Participant (Pecheur + Equipe)
CREATE TABLE participants (
    id_user INT REFERENCES pecheurs(id_user) ON DELETE CASCADE,
    id_equipe INT REFERENCES equipes(id_equipe) ON DELETE CASCADE,
    score INT DEFAULT 0,
    PRIMARY KEY (id_user, id_equipe)
);

-- 4. Fishing Activity
CREATE TABLE prises (
    id_prise INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poids_prise FLOAT,
    taille_prise FLOAT,
    nom_prise VARCHAR(255),
    photo_prise VARCHAR(255),
    date_heure TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    statut VARCHAR(50),
    mode VARCHAR(50), -- e.g., 'relâché' or 'gardé'
    statut_prise VARCHAR(50),
    spot_prise VARCHAR(255),
    id_user INT REFERENCES pecheurs(id_user) ON DELETE CASCADE,
    id_espece INT REFERENCES especes(id_espece) ON DELETE SET NULL,
    id_competition INT REFERENCES competitions(id_competition) ON DELETE SET NULL
);

-- 5. Interactions & Social features
CREATE TABLE commentaires (
    id_commentaire INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenu TEXT,
    date_commentaire DATE DEFAULT CURRENT_DATE,
    statut_commentaire BOOLEAN DEFAULT TRUE,
    id_user INT REFERENCES fans(id_user) ON DELETE CASCADE,
    id_prise INT REFERENCES prises(id_prise) ON DELETE CASCADE
);

-- 'Like' associations (Simplified inheritance)
CREATE TABLE like_pecheurs (
    id_fan INT REFERENCES fans(id_user) ON DELETE CASCADE,
    id_pecheur INT REFERENCES pecheurs(id_user) ON DELETE CASCADE,
    statut_like BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id_fan, id_pecheur)
);

CREATE TABLE like_prises (
    id_fan INT REFERENCES fans(id_user) ON DELETE CASCADE,
    id_prise INT REFERENCES prises(id_prise) ON DELETE CASCADE,
    statut_like BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id_fan, id_prise)
);

CREATE TABLE like_competitions (
    id_fan INT REFERENCES fans(id_user) ON DELETE CASCADE,
    id_competition INT REFERENCES competitions(id_competition) ON DELETE CASCADE,
    statut_like BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (id_fan, id_competition)
);

-- Many-to-Many: Fan and Badges
CREATE TABLE fan_badges (
    id_user INT REFERENCES fans(id_user) ON DELETE CASCADE,
    id_badge INT REFERENCES badges(id_badge) ON DELETE CASCADE,
    PRIMARY KEY (id_user, id_badge)
);